<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdvancedWebDevelopmentServicesSeeder extends Seeder
{
    public function run()
    {
        DB::table('service_plans')->insert([
            [
                'name' => 'Personalized Digital Strategies - Basic',
                'description' => 'Tailored Strategy Planning, Basic Data Analytics, and 2 Revisions.',
                'monthly_price' => 49.99,
                'annual_price' => 499.99,
                'lifetime_price' => 999.99,
                'tier' => 'basic',
                'features' => json_encode([
                    'Tailored Strategy Planning',
                    'Basic Data Analytics',
                    '2 Revisions'
                ]),
                'additional_services' => json_encode([
                    'Basic SEO Optimization',
                    'Social Media Setup',
                    '24/7 Email Support',
                    'Monthly Performance Report',
                    'Basic Website Audit',
                    'Content Strategy Consultation',
                    'Basic Competitor Analysis',
                    'Keyword Research',
                    'Content Calendar Creation',
                    'Social Media Integration',
                    'Basic CRM Setup'
                ]),
                'support_level' => 'Standard Support',
                'max_users' => 1,
                'tags' => json_encode(['digital strategy', 'basic']),
                'filters' => json_encode(['Strategy Planning']),
                'restrictions' => json_encode(['Limited to 2 revisions']),
                'status' => 'active',
                'discount' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Personalized Digital Strategies - Standard',
                'description' => 'Comprehensive Strategy Planning, Advanced Data Analytics, and 5 Revisions.',
                'monthly_price' => 99.99,
                'annual_price' => 999.99,
                'lifetime_price' => 1999.99,
                'tier' => 'standard',
                'features' => json_encode([
                    'Comprehensive Strategy Planning',
                    'Advanced Data Analytics',
                    '5 Revisions'
                ]),
                'additional_services' => json_encode([
                    'Enhanced SEO Optimization',
                    'Social Media Strategy and Management',
                    '24/7 Email and Phone Support',
                    'Weekly Performance Report',
                    'In-Depth Website Audit',
                    'Advanced Content Strategy',
                    'Competitor Analysis',
                    'Keyword Strategy Development',
                    'Content Creation & Scheduling',
                    'Social Media Advertising Strategy',
                    'CRM Integration & Setup',
                    'Monthly A/B Testing'
                ]),
                'support_level' => 'Priority Support',
                'max_users' => 3,
                'tags' => json_encode(['digital strategy', 'standard']),
                'filters' => json_encode(['Advanced Strategy Planning']),
                'restrictions' => json_encode(['Limited to 5 revisions']),
                'status' => 'active',
                'discount' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Personalized Digital Strategies - Premium',
                'description' => 'Full Custom Strategy Development, Expert Data Analytics, and Unlimited Revisions.',
                'monthly_price' => 149.99,
                'annual_price' => 1499.99,
                'lifetime_price' => 2999.99,
                'tier' => 'premium',
                'features' => json_encode([
                    'Full Custom Strategy Development',
                    'Expert Data Analytics',
                    'Unlimited Revisions'
                ]),
                'additional_services' => json_encode([
                    'Premium SEO Optimization',
                    'Comprehensive Social Media Campaigns',
                    '24/7 Multichannel Support',
                    'Daily Performance Reports',
                    'Full Website Optimization',
                    'Content Strategy & Creation',
                    'In-Depth Competitor Analysis',
                    'Advanced Keyword Optimization',
                    'Omnichannel Content Distribution',
                    'Advanced Social Media Advertising',
                    'CRM Integration with Automation',
                    'Real-Time A/B Testing & Optimization',
                    'Custom Marketing Dashboard'
                ]),
                'support_level' => '24/7 Dedicated Support',
                'max_users' => 5,
                'tags' => json_encode(['digital strategy', 'premium']),
                'filters' => json_encode(['Custom Strategy Development']),
                'restrictions' => json_encode(['Unlimited revisions']),
                'status' => 'active',
                'discount' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Data-Driven Insights - Basic',
                'description' => 'Foundational Data Analysis, Key Metrics Tracking, and Basic Reporting.',
                'monthly_price' => 49.99,
                'annual_price' => 499.99,
                'lifetime_price' => 999.99,
                'tier' => 'basic',
                'features' => json_encode([
                    'Foundational Data Analysis',
                    'Key Metrics Tracking',
                    'Basic Reporting'
                ]),
                'additional_services' => json_encode([
                    'Basic Visualization Tools',
                    'Custom Report Generation',
                    'Email Support',
                    'Weekly Performance Dashboard',
                    'Basic Google Analytics Setup',
                    'Traffic Source Analysis',
                    'Basic Conversion Tracking',
                    'User Behavior Analysis',
                    'Monthly Data Review',
                    'Heatmap Integration',
                    'Basic A/B Testing Insights'
                ]),
                'support_level' => 'Standard Support',
                'max_users' => 1,
                'tags' => json_encode(['data analysis', 'basic']),
                'filters' => json_encode(['Data Tracking']),
                'restrictions' => json_encode(['Limited to standard data sets']),
                'status' => 'active',
                'discount' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Data-Driven Insights - Standard',
                'description' => 'Advanced Data Analysis, Custom Metrics, and In-Depth Reporting.',
                'monthly_price' => 99.99,
                'annual_price' => 999.99,
                'lifetime_price' => 1999.99,
                'tier' => 'standard',
                'features' => json_encode([
                    'Advanced Data Analysis',
                    'Custom Metrics Tracking',
                    'In-Depth Reporting'
                ]),
                'additional_services' => json_encode([
                    'Advanced Visualization Tools',
                    'Custom Report Scheduling',
                    'Phone and Email Support',
                    'Daily Performance Dashboard',
                    'Advanced Google Analytics Setup',
                    'Enhanced Traffic Source Analysis',
                    'Conversion Funnel Analysis',
                    'Advanced User Behavior Insights',
                    'Weekly Data Review',
                    'Dynamic Heatmap Integration',
                    'Advanced A/B Testing Insights',
                    'Customer Segmentation Analysis'
                ]),
                'support_level' => 'Priority Support',
                'max_users' => 3,
                'tags' => json_encode(['data analysis', 'standard']),
                'filters' => json_encode(['Advanced Data Tracking']),
                'restrictions' => json_encode(['Extended data sets']),
                'status' => 'active',
                'discount' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Data-Driven Insights - Premium',
                'description' => 'Comprehensive Data Strategy, Predictive Analytics, and Real-Time Reporting.',
                'monthly_price' => 149.99,
                'annual_price' => 1499.99,
                'lifetime_price' => 2999.99,
                'tier' => 'premium',
                'features' => json_encode([
                    'Comprehensive Data Strategy',
                    'Predictive Analytics',
                    'Real-Time Reporting'
                ]),
                'additional_services' => json_encode([
                    'Premium Visualization Dashboards',
                    'Automated Report Distribution',
                    '24/7 Multichannel Support',
                    'Real-Time Performance Dashboard',
                    'Custom Google Analytics Integration',
                    'Comprehensive Traffic Source Analysis',
                    'Predictive Conversion Modeling',
                    'Advanced User Segmentation',
                    'Daily Data Review & Optimization',
                    'Interactive Heatmap Tools',
                    'Machine Learning-Based A/B Testing',
                    'Custom Data Integration Solutions',
                    'Enterprise-Level Data Security'
                ]),
                'support_level' => '24/7 Dedicated Support',
                'max_users' => 5,
                'tags' => json_encode(['data analysis', 'premium']),
                'filters' => json_encode(['Predictive Analytics']),
                'restrictions' => json_encode(['Unlimited data sets']),
                'status' => 'active',
                'discount' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Innovative Design - Basic',
                'description' => 'Essential design services to create visually appealing websites and graphics.',
                'monthly_price' => 49.99,
                'annual_price' => 499.99,
                'lifetime_price' => 999.99,
                'tier' => 'basic',
                'features' => json_encode([
                    'Basic Web Design',
                    'Graphic Design',
                    'Logo Creation'
                ]),
                'additional_services' => json_encode([
                    'Basic UX/UI Design',
                    'Color Scheme Development',
                    'Email Support',
                    'Responsive Design',
                    'Basic Image Editing',
                    'Typography Selection',
                    'Basic Branding Guidelines',
                    'Social Media Graphics',
                    'Basic Iconography',
                    'Newsletter Template Design',
                    'One-Page Website Design'
                ]),
                'support_level' => 'Standard Support',
                'max_users' => 1,
                'tags' => json_encode(['design', 'basic']),
                'filters' => json_encode(['Visual Design']),
                'restrictions' => json_encode(['Limited to basic design packages']),
                'status' => 'active',
                'discount' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Innovative Design - Standard',
                'description' => 'Advanced design services including custom graphics and enhanced web design.',
                'monthly_price' => 99.99,
                'annual_price' => 999.99,
                'lifetime_price' => 1999.99,
                'tier' => 'standard',
                'features' => json_encode([
                    'Advanced Web Design',
                    'Custom Graphic Design',
                    'Interactive Elements'
                ]),
                'additional_services' => json_encode([
                    'Advanced UX/UI Design',
                    'Branding Strategy Development',
                    'Phone and Email Support',
                    'Advanced Responsive Design',
                    'High-Quality Image Editing',
                    'Custom Typography',
                    'Advanced Branding Guidelines',
                    'Custom Social Media Graphics',
                    'Custom Iconography',
                    'Multi-Page Website Design',
                    'Custom Newsletter Design',
                    'Basic Animation Creation'
                ]),
                'support_level' => 'Priority Support',
                'max_users' => 3,
                'tags' => json_encode(['design', 'standard']),
                'filters' => json_encode(['Enhanced Visual Design']),
                'restrictions' => json_encode(['Extended design packages']),
                'status' => 'active',
                'discount' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Innovative Design - Premium',
                'description' => 'Comprehensive design services with cutting-edge technology and custom solutions.',
                'monthly_price' => 149.99,
                'annual_price' => 1499.99,
                'lifetime_price' => 2999.99,
                'tier' => 'premium',
                'features' => json_encode([
                    'Custom Web Design',
                    '3D Graphic Design',
                    'Animation and Video'
                ]),
                'additional_services' => json_encode([
                    'Premium UX/UI Design',
                    'Full Branding Package',
                    '24/7 Multichannel Support',
                    'Advanced Animation & Video Production',
                    '3D Modeling & Rendering',
                    'Custom Interactive Elements',
                    'Complete Branding Guidelines',
                    'Advanced Social Media Campaign Graphics',
                    'Premium Iconography',
                    'Custom Multi-Page Website Design',
                    'High-End Newsletter Design',
                    'Custom E-commerce Design Solutions',
                    'Virtual Reality Interface Design'
                ]),
                'support_level' => '24/7 Dedicated Support',
                'max_users' => 5,
                'tags' => json_encode(['design', 'premium']),
                'filters' => json_encode(['Comprehensive Visual Design']),
                'restrictions' => json_encode(['Unlimited design packages']),
                'status' => 'active',
                'discount' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        [
            'name' => 'SEO Mastery - Basic',
            'description' => 'Essential SEO services to improve your website\'s visibility and rankings.',
            'monthly_price' => 49.99,
            'annual_price' => 499.99,
            'lifetime_price' => 999.99,
            'tier' => 'basic',
            'features' => json_encode(['Keyword Research', 'On-Page Optimization', 'Basic Reporting']),
            'additional_services' => json_encode(['Meta Tag Optimization', 'XML Sitemap Creation', 'Email Support']),
            'support_level' => 'Standard Support',
            'max_users' => 1,
            'tags' => json_encode(['SEO', 'basic']),
            'filters' => json_encode(['Search Engine Optimization']),
            'restrictions' => json_encode(['Limited to basic SEO services']),
            'status' => 'active',
            'discount' => 10,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'SEO Mastery - Basic',
            'description' => 'Essential SEO services to improve your website\'s visibility and rankings.',
            'monthly_price' => 49.99,
            'annual_price' => 499.99,
            'lifetime_price' => 999.99,
            'tier' => 'basic',
            'features' => json_encode([
                'Keyword Research',
                'On-Page Optimization',
                'Basic Reporting'
            ]),
            'additional_services' => json_encode([
                'Meta Tag Optimization',
                'XML Sitemap Creation',
                'Email Support',
                'Google My Business Setup',
                'Basic Local SEO',
                'Image Alt Text Optimization',
                'Basic Page Speed Optimization',
                'Mobile SEO Optimization',
                'Basic Competitor SEO Analysis',
                'Basic Link Building',
                'SEO-Friendly Content Creation'
            ]),
            'support_level' => 'Standard Support',
            'max_users' => 1,
            'tags' => json_encode(['SEO', 'basic']),
            'filters' => json_encode(['Search Engine Optimization']),
            'restrictions' => json_encode(['Limited to basic SEO services']),
            'status' => 'active',
            'discount' => 10,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'SEO Mastery - Standard',
            'description' => 'Advanced SEO services to boost your search engine rankings and drive more traffic.',
            'monthly_price' => 99.99,
            'annual_price' => 999.99,
            'lifetime_price' => 1999.99,
            'tier' => 'standard',
            'features' => json_encode([
                'Advanced Keyword Research',
                'Technical SEO Audit',
                'Content Optimization'
            ]),
            'additional_services' => json_encode([
                'Backlink Analysis',
                'Competitor Analysis',
                'Phone and Email Support',
                'Advanced Local SEO',
                'Schema Markup Implementation',
                'Advanced Page Speed Optimization',
                'Content Strategy Development',
                'Voice Search Optimization',
                'Advanced Link Building',
                'Weekly SEO Reports',
                'Google Analytics & Search Console Integration',
                'Landing Page Optimization'
            ]),
            'support_level' => 'Priority Support',
            'max_users' => 3,
            'tags' => json_encode(['SEO', 'standard']),
            'filters' => json_encode(['Advanced SEO Strategies']),
            'restrictions' => json_encode(['Extended SEO services']),
            'status' => 'active',
            'discount' => 15,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'SEO Mastery - Premium',
            'description' => 'Comprehensive SEO services with a focus on achieving top rankings and maximum visibility.',
            'monthly_price' => 149.99,
            'annual_price' => 1499.99,
            'lifetime_price' => 2999.99,
            'tier' => 'premium',
            'features' => json_encode([
                'Comprehensive SEO Strategy',
                'Full Technical SEO Audit',
                'Custom Content Creation'
            ]),
            'additional_services' => json_encode([
                'Link Building Campaigns',
                'Ongoing SEO Monitoring',
                '24/7 Dedicated Support',
                'International SEO Strategy',
                'Advanced Schema Markup',
                'Content Marketing Integration',
                'Multilingual SEO Support',
                'E-commerce SEO Optimization',
                'Advanced Voice Search Optimization',
                'Advanced Google Analytics Configuration',
                'Custom SEO Dashboard',
                'Enterprise-Level SEO Solutions',
                'AI-Powered SEO Tools Integration'
            ]),
            'support_level' => '24/7 Dedicated Support',
            'max_users' => 5,
            'tags' => json_encode(['SEO', 'premium']),
            'filters' => json_encode(['Complete SEO Solutions']),
            'restrictions' => json_encode(['Unlimited SEO services']),
            'status' => 'active',
            'discount' => 20,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Personalized Digital Strategies - Free',
            'description' => 'Basic digital strategy insights and initial consultation at no cost.',
            'monthly_price' => 0.00,
            'annual_price' => 0.00,
            'lifetime_price' => 0.00,
            'tier' => 'free',
            'features' => json_encode([
                'Initial Strategy Consultation',
                'Basic Competitor Overview',
                'Social Media Presence Review'
            ]),
            'additional_services' => json_encode([
                'Basic SEO Tips',
                'Content Strategy Starter Guide',
                'Social Media Tips for Beginners',
                'Monthly Email Support'
            ]),
            'support_level' => 'Email Support',
            'max_users' => 1,
            'tags' => json_encode(['digital strategy', 'free']),
            'filters' => json_encode(['Basic Strategy Insights']),
            'restrictions' => json_encode(['Limited to basic consultation']),
            'status' => 'active',
            'discount' => 0,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Innovative Design - Free',
            'description' => 'Basic design services including simple logo creation and web template suggestions.',
            'monthly_price' => 0.00,
            'annual_price' => 0.00,
            'lifetime_price' => 0.00,
            'tier' => 'free',
            'features' => json_encode([
                'Basic Logo Design',
                'Web Template Suggestions',
                'Color Scheme Ideas'
            ]),
            'additional_services' => json_encode([
                'Basic UX/UI Tips',
                'Simple Graphic Design Tools',
                'Social Media Graphic Templates',
                'Monthly Design Tips Newsletter'
            ]),
            'support_level' => 'Email Support',
            'max_users' => 1,
            'tags' => json_encode(['design', 'free']),
            'filters' => json_encode(['Basic Design Services']),
            'restrictions' => json_encode(['Limited to basic designs']),
            'status' => 'active',
            'discount' => 0,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'Innovative Design - Free',
            'description' => 'Basic design services including simple logo creation and web template suggestions.',
            'monthly_price' => 0.00,
            'annual_price' => 0.00,
            'lifetime_price' => 0.00,
            'tier' => 'free',
            'features' => json_encode([
                'Basic Logo Design',
                'Web Template Suggestions',
                'Color Scheme Ideas'
            ]),
            'additional_services' => json_encode([
                'Basic UX/UI Tips',
                'Simple Graphic Design Tools',
                'Social Media Graphic Templates',
                'Monthly Design Tips Newsletter'
            ]),
            'support_level' => 'Email Support',
            'max_users' => 1,
            'tags' => json_encode(['design', 'free']),
            'filters' => json_encode(['Basic Design Services']),
            'restrictions' => json_encode(['Limited to basic designs']),
            'status' => 'active',
            'discount' => 0,
            'created_at' => now(),
            'updated_at' => now(),
        ],

        ]);
    }
}
