<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TemplatesSeeder extends Seeder
{
    public function run()
    {
        $templates = [
            [
                'title' => 'Article Creator',
                'category' => 'templates-blog',
                'description' => 'Effortlessly generate unique, engaging articles tailored to any topic, enhancing audience engagement and boosting SEO performance.',
                'icon' => 'fas fa-newspaper',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Customer Review Builder',
                'category' => 'templates-ecommerce',
                'description' => 'Instantly generate authentic customer testimonials to build trust, credibility, and improve conversion rates.',
                'icon' => 'fas fa-star',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Blog Conclusion Enhancer',
                'category' => 'templates-blog',
                'description' => 'Craft impactful conclusions for your blog posts that leave a lasting impression and encourage reader action.',
                'icon' => 'fas fa-bookmark',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'YouTube Content Optimizer',
                'category' => 'templates-social-media',
                'description' => 'Enhance your YouTube videos with optimized descriptions that increase views and engagement, tailored to your target audience.',
                'icon' => 'fab fa-youtube',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Instagram Caption Master',
                'category' => 'templates-social-media',
                'description' => 'Create captivating Instagram captions designed to engage followers, boost reach, and drive interaction on every post.',
                'icon' => 'fab fa-instagram',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Tweet Creator',
                'category' => 'templates-social-media',
                'description' => 'Generate compelling tweets that capture attention and spark engagement, perfect for growing your Twitter presence.',
                'icon' => 'fab fa-twitter',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Facebook Headline Generator',
                'category' => 'templates-social-media',
                'description' => 'Craft attention-grabbing Facebook headlines that increase post visibility, drive traffic, and boost engagement.',
                'icon' => 'fab fa-facebook',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Google Ads Headline Creator',
                'category' => 'templates-advertisement',
                'description' => 'Develop high-converting Google Ads headlines that captivate potential customers and drive traffic to your site.',
                'icon' => 'fab fa-google',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Content Paragraph Generator',
                'category' => 'templates-blog',
                'description' => 'Generate perfectly structured paragraphs with optimized keywords to maintain flow and captivate your audience.',
                'icon' => 'fas fa-paragraph',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Decision Maker Pro & Con Analyzer',
                'category' => 'templates-development',
                'description' => 'Create comprehensive pros and cons lists to facilitate informed decision-making for any business strategy.',
                'icon' => 'fas fa-list',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'SEO Meta Description Builder',
                'category' => 'templates-development',
                'description' => 'Develop SEO-optimized meta descriptions that improve click-through rates and attract targeted traffic to your website.',
                'icon' => 'fas fa-clipboard',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Product Description Specialist',
                'category' => 'templates-ecommerce',
                'description' => 'Craft persuasive product descriptions that highlight key features and benefits, boosting online sales and customer satisfaction.',
                'icon' => 'fas fa-pen',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Instagram Hashtag Optimizer',
                'category' => 'templates-social-media',
                'description' => 'Generate trending, relevant hashtags to maximize your Instagram reach and increase content discoverability.',
                'icon' => 'fab fa-instagram',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Business Social Media Content Creator',
                'category' => 'templates-social-media',
                'description' => 'Create professional, impactful content tailored for business social media profiles to enhance brand presence and engagement.',
                'icon' => 'fas fa-building',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Google Ads Copywriter',
                'category' => 'templates-advertisement',
                'description' => 'Generate high-impact ad copy that attracts clicks and drives conversions in your Google Ads campaigns.',
                'icon' => 'fab fa-google',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'FAQ Content Generator',
                'category' => 'templates-development',
                'description' => 'Quickly create customized FAQs that answer common customer questions, enhancing user experience and SEO.',
                'icon' => 'fas fa-question-circle',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Email Campaign Generator',
                'category' => 'templates-email',
                'description' => 'Develop targeted email campaigns with compelling content that boosts engagement and drives conversions.',
                'icon' => 'fas fa-envelope',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Email Response Builder',
                'category' => 'templates-email',
                'description' => 'Create professional, personalized responses to customer queries, enhancing communication and customer service.',
                'icon' => 'fas fa-reply',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Newsletter Content Creator',
                'category' => 'templates-email',
                'description' => 'Generate engaging, personalized newsletter content to keep your audience informed, interested, and engaged.',
                'icon' => 'fas fa-newspaper',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Grammar and Style Checker',
                'category' => 'templates-blog',
                'description' => 'Enhance your content with perfect grammar and style corrections for polished, professional writing.',
                'icon' => 'fas fa-spell-check',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Content Summarization Tool',
                'category' => 'templates-blog',
                'description' => 'Automatically condense lengthy texts into concise summaries to save time and improve readability.',
                'icon' => 'fas fa-compress-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI Article Wizard',
                'category' => 'templates-blog',
                'description' => 'Instantly generate high-quality, custom articles tailored to your brand\'s voice and audience preferences.',
                'icon' => 'fas fa-magic',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'File Insight Extractor',
                'category' => 'templates-blog',
                'description' => 'Upload any document (PDF, CSV, DOC) and extract key insights or summaries with ease.',
                'icon' => 'fas fa-file-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Visual Content Generator',
                'category' => 'templates-blog',
                'description' => 'Create custom images based on user input, perfect for enhancing digital content and campaigns.',
                'icon' => 'fas fa-image',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI Rewriter Pro',
                'category' => 'templates-blog',
                'description' => 'Instantly rewrite content to be more professional and detailed, boosting engagement and readability.',
                'icon' => 'fas fa-redo',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'RSS Content Curator',
                'category' => 'templates-rss',
                'description' => 'Automatically generate unique content from RSS feeds to keep your website updated with fresh material.',
                'icon' => 'fas fa-rss',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI Content Detection Tool',
                'category' => 'templates-blog',
                'description' => 'Detect AI-generated text and maintain content authenticity across your platforms.',
                'icon' => 'fas fa-search',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Professional Cover Letter Builder',
                'category' => 'templates-academic',
                'description' => 'Generate impactful cover letters that highlight your strengths and grab the attention of potential employers.',
                'icon' => 'fas fa-file-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Advanced Math Solver',
                'category' => 'templates-academic',
                'description' => 'Quickly solve complex math problems with step-by-step solutions to enhance understanding.',
                'icon' => 'fas fa-calculator',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Thesis Statement Generator',
                'category' => 'templates-academic',
                'description' => 'Create strong, clear thesis statements for academic papers or essays in seconds.',
                'icon' => 'fas fa-quote-right',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Proofreading Assistant',
                'category' => 'templates-academic',
                'description' => 'Automatically proofread content and suggest improvements for grammar, clarity, and style.',
                'icon' => 'fas fa-check',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Content Rephraser',
                'category' => 'templates-academic',
                'description' => 'Rephrase content for better clarity, engagement, and readability while retaining the original message.',
                'icon' => 'fas fa-sync-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Content Improvement Tool',
                'category' => 'templates-academic',
                'description' => 'Improve the quality of your text by suggesting enhancements and edits for clarity and impact.',
                'icon' => 'fas fa-arrow-up',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Job Description Generator',
                'category' => 'templates-business',
                'description' => 'Develop detailed job descriptions tailored to specific roles to attract the right candidates.',
                'icon' => 'fas fa-briefcase',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Resume Builder',
                'category' => 'templates-business',
                'description' => 'Create professional resumes that highlight your skills and experiences to stand out to employers.',
                'icon' => 'fas fa-file-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'LinkedIn Profile Generator',
                'category' => 'templates-business',
                'description' => 'Optimize your LinkedIn profile with compelling descriptions that attract attention from employers.',
                'icon' => 'fab fa-linkedin',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Startup Idea Generator',
                'category' => 'templates-business',
                'description' => 'Generate innovative startup ideas with market analysis to identify opportunities for growth.',
                'icon' => 'fas fa-lightbulb',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'PAS Framework Creator',
                'category' => 'templates-business',
                'description' => 'Develop Persuasion-Awareness-Solution frameworks to enhance your communication strategies.',
                'icon' => 'fas fa-bullhorn',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Strategic Plan Generator',
                'category' => 'templates-business',
                'description' => 'Create comprehensive strategic plans to drive business development and achieve growth objectives.',
                'icon' => 'fas fa-chart-line',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Personal Bio Writer',
                'category' => 'templates-business',
                'description' => 'Generate compelling personal biographies for professional profiles, portfolios, and networking.',
                'icon' => 'fas fa-user',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Cost-Benefit Analysis Tool',
                'category' => 'templates-business',
                'description' => 'Conduct detailed cost-benefit analyses to evaluate business decisions and investments.',
                'icon' => 'fas fa-balance-scale',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Creative Brainstorming Tool',
                'category' => 'templates-business',
                'description' => 'Facilitate innovative idea generation sessions to solve problems or develop new strategies.',
                'icon' => 'fas fa-brain',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'LinkedIn Post Generator',
                'category' => 'templates-business',
                'description' => 'Create engaging, professional posts for LinkedIn to enhance your brand\'s presence and reach.',
                'icon' => 'fab fa-linkedin',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Sales Pitch Creator',
                'category' => 'templates-business',
                'description' => 'Craft persuasive sales pitches to attract potential clients, investors, and partners.',
                'icon' => 'fas fa-handshake',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Social Media Reply Generator',
                'category' => 'templates-customer-service',
                'description' => 'Generate effective replies to social media comments and messages, maintaining a positive brand image.',
                'icon' => 'fas fa-reply',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Customer Support Ticket Reply',
                'category' => 'templates-customer-service',
                'description' => 'Create professional responses for customer support tickets to resolve issues promptly and effectively.',
                'icon' => 'fas fa-ticket-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Song Lyrics Generator',
                'category' => 'templates-entertainment',
                'description' => 'Generate original song lyrics across various genres to inspire creativity and composition.',
                'icon' => 'fas fa-music',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Joke Generator',
                'category' => 'templates-entertainment',
                'description' => 'Create funny jokes to entertain and amuse your audience, perfect for social media or marketing.',
                'icon' => 'fas fa-laugh',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Event Itinerary Planner',
                'category' => 'templates-entertainment',
                'description' => 'Design detailed itineraries for events, ensuring a seamless and enjoyable experience for attendees.',
                'icon' => 'fas fa-calendar-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Travel Plan Creator',
                'category' => 'templates-entertainment',
                'description' => 'Develop personalized travel plans tailored to specific destinations and traveler preferences.',
                'icon' => 'fas fa-plane-departure',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Gift Idea Generator',
                'category' => 'templates-entertainment',
                'description' => 'Discover creative gift ideas personalized for any occasion or recipient.',
                'icon' => 'fas fa-gift',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Product Feature Highlighter',
                'category' => 'templates-ecommerce',
                'description' => 'Emphasize the key features of a product to make it more attractive to potential customers.',
                'icon' => 'fas fa-list',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Product Naming Tool',
                'category' => 'templates-ecommerce',
                'description' => 'Generate creative and memorable names for new products to enhance brand identity.',
                'icon' => 'fas fa-tags',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Product Comparison Generator',
                'category' => 'templates-ecommerce',
                'description' => 'Explain why your product stands out from competitors by highlighting unique features and benefits.',
                'icon' => 'fas fa-thumbs-up',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Product Review Generator',
                'category' => 'templates-ecommerce',
                'description' => 'Generate in-depth, authentic product reviews that build trust and influence purchase decisions.',
                'icon' => 'fas fa-clipboard-list',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Customer Review Response Tool',
                'category' => 'templates-ecommerce',
                'description' => 'Craft thoughtful and professional responses to customer reviews, enhancing brand reputation.',
                'icon' => 'fas fa-comment-dots',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Website Sitemap Builder',
                'category' => 'templates-website',
                'description' => 'Generate a complete sitemap for your website to improve navigation and SEO.',
                'icon' => 'fas fa-sitemap',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Website Tagline Creator',
                'category' => 'templates-website',
                'description' => 'Develop catchy and memorable taglines to effectively convey your brand\'s message.',
                'icon' => 'fas fa-tag',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'UX Enhancement Ideas',
                'category' => 'templates-website',
                'description' => 'Generate innovative ideas to improve the user experience on your website or app.',
                'icon' => 'fas fa-lightbulb',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Website Design Ideas',
                'category' => 'templates-website',
                'description' => 'Get creative design concepts for your website to enhance its visual appeal and usability.',
                'icon' => 'fas fa-paint-brush',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Service Page Content Generator',
                'category' => 'templates-website',
                'description' => 'Create detailed content for your service pages to effectively communicate your offerings.',
                'icon' => 'fas fa-concierge-bell',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Features Page Content Builder',
                'category' => 'templates-website',
                'description' => 'Generate compelling content for your features page to highlight the benefits of your product or service.',
                'icon' => 'fas fa-star',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Keyword Research Tool',
                'category' => 'templates-website',
                'description' => 'Generate a list of relevant keywords for your website to enhance SEO and drive traffic.',
                'icon' => 'fas fa-key',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Keyword Extraction Tool',
                'category' => 'templates-website',
                'description' => 'Extract important keywords from your website content to improve SEO strategy.',
                'icon' => 'fas fa-search',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'SEO Content Creator',
                'category' => 'templates-website',
                'description' => 'Optimize your website content for search engines to increase visibility and traffic.',
                'icon' => 'fas fa-search-plus',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Testimonial Generator',
                'category' => 'templates-website',
                'description' => 'Create authentic testimonials to build trust and credibility on your website.',
                'icon' => 'fas fa-comments',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Landing Page Copywriter',
                'category' => 'templates-website',
                'description' => 'Craft persuasive copy for your landing pages to convert visitors into customers.',
                'icon' => 'fas fa-copy',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Website Copywriting Tool',
                'category' => 'templates-website',
                'description' => 'Create engaging, high-quality content for various pages on your website.',
                'icon' => 'fas fa-feather-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Website FAQ Generator',
                'category' => 'templates-website',
                'description' => 'Generate comprehensive FAQs to address common customer queries and enhance user experience.',
                'icon' => 'fas fa-question-circle',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Call to Action Creator',
                'category' => 'templates-website',
                'description' => 'Develop effective calls to action that encourage visitors to take desired steps on your website.',
                'icon' => 'fas fa-bullhorn',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Meta Description Generator',
                'category' => 'templates-website',
                'description' => 'Create SEO-friendly meta descriptions for your website pages to improve search engine rankings.',
                'icon' => 'fas fa-info-circle',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Keyword-Based Content Rewriter',
                'category' => 'templates-website',
                'description' => 'Rewrite website content with targeted keywords to boost SEO and audience engagement.',
                'icon' => 'fas fa-edit',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Privacy Policy Generator',
                'category' => 'templates-website',
                'description' => 'Create a customized privacy policy for your website to comply with legal requirements.',
                'icon' => 'fas fa-user-secret',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Terms and Conditions Generator',
                'category' => 'templates-website',
                'description' => 'Generate tailored terms and conditions to protect your business and users on your website.',
                'icon' => 'fas fa-file-contract',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Blog Idea Generator',
                'category' => 'templates-blog',
                'description' => 'Generate creative and engaging ideas for your next blog post to attract more readers.',
                'icon' => 'fas fa-pencil-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Blog Introduction Generator',
                'category' => 'templates-blog',
                'description' => 'Craft an engaging introduction for your blog posts to captivate readers from the start.',
                'icon' => 'fas fa-quote-left',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Blog Section Generator',
                'category' => 'templates-blog',
                'description' => 'Create well-structured sections for your blog posts to maintain reader interest and flow.',
                'icon' => 'fas fa-paragraph',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Blog Outline Builder',
                'category' => 'templates-blog',
                'description' => 'Generate a comprehensive outline for your blog posts to organize content effectively.',
                'icon' => 'fas fa-tasks',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Full Blog Article Generator',
                'category' => 'templates-blog',
                'description' => 'Instantly generate a complete blog article tailored to your topic and audience.',
                'icon' => 'fas fa-newspaper',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Instagram Reel Script Generator',
                'category' => 'templates-social-media',
                'description' => 'Create engaging scripts for Instagram Reels to capture attention and boost engagement.',
                'icon' => 'fas fa-video',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'TikTok Video Script Creator',
                'category' => 'templates-social-media',
                'description' => 'Generate creative scripts for TikTok videos to maximize views and interaction.',
                'icon' => 'fab fa-tiktok',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Facebook Post Generator',
                'category' => 'templates-social-media',
                'description' => 'Generate compelling Facebook posts that drive engagement and expand reach.',
                'icon' => 'fab fa-facebook',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Tweet Idea Generator',
                'category' => 'templates-social-media',
                'description' => 'Develop creative tweet ideas to capture attention and increase Twitter engagement.',
                'icon' => 'fab fa-twitter',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Twitter Thread Creator',
                'category' => 'templates-social-media',
                'description' => 'Craft engaging Twitter threads on any topic to stimulate conversation and grow followers.',
                'icon' => 'fas fa-comments',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'YouTube Video Title Generator',
                'category' => 'templates-social-media',
                'description' => 'Generate catchy titles for YouTube videos to increase click-through rates and views.',
                'icon' => 'fab fa-youtube',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Video Description Generator',
                'category' => 'templates-social-media',
                'description' => 'Craft compelling video descriptions to enhance engagement and viewer retention.',
                'icon' => 'fas fa-file-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Viral Tweet Idea Generator',
                'category' => 'templates-social-media',
                'description' => 'Generate creative ideas for tweets that have the potential to go viral.',
                'icon' => 'fab fa-twitter',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Clickbait Headline Generator',
                'category' => 'templates-social-media',
                'description' => 'Create attention-grabbing headlines for social media posts to boost engagement.',
                'icon' => 'fas fa-bullhorn',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Facebook Ad Generator',
                'category' => 'templates-advertising',
                'description' => 'Generate effective content for Facebook ads to attract clicks and drive conversions.',
                'icon' => 'fab fa-facebook',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Google Ad Content Generator',
                'category' => 'templates-advertising',
                'description' => 'Create compelling content for Google ads to increase click-through rates and conversions.',
                'icon' => 'fab fa-google',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'TV Advertisement Script Creator',
                'category' => 'templates-advertising',
                'description' => 'Develop engaging scripts for TV advertisements to capture audience attention.',
                'icon' => 'fas fa-tv',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'YouTube Ad Creator',
                'category' => 'templates-advertising',
                'description' => 'Generate creative ideas and scripts for YouTube ads to maximize reach and impact.',
                'icon' => 'fab fa-youtube',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Language Translation Tool',
                'category' => 'templates-languages',
                'description' => 'Translate text accurately from one language to another for effective communication.',
                'icon' => 'fas fa-language',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Grammar Checker Tool',
                'category' => 'templates-languages',
                'description' => 'Check and correct grammar mistakes to enhance the quality of your writing.',
                'icon' => 'fas fa-spell-check',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Synonym Finder',
                'category' => 'templates-languages',
                'description' => 'Generate synonyms for any word to diversify your vocabulary and enhance writing.',
                'icon' => 'fas fa-th-list',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Vocabulary Builder',
                'category' => 'templates-languages',
                'description' => 'Discover and learn new words with their meanings and contextual usage.',
                'icon' => 'fas fa-book',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Bug Fixer Tool',
                'category' => 'templates-development',
                'description' => 'Identify and fix code bugs to improve functionality and performance.',
                'icon' => 'fas fa-bug',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Code Explanation Generator',
                'category' => 'templates-development',
                'description' => 'Provide clear explanations and clarifications for specific sections of code.',
                'icon' => 'fas fa-code',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Welcome Email Creator',
                'category' => 'templates-email',
                'description' => 'Design a warm and engaging welcome email to greet new subscribers or users.',
                'icon' => 'fas fa-envelope-open-text',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Event Invitation Email',
                'category' => 'templates-email',
                'description' => 'Craft a compelling invitation email for events, gatherings, or meetings.',
                'icon' => 'fas fa-envelope',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Follow-Up Email Composer',
                'category' => 'templates-email',
                'description' => 'Create effective follow-up emails to reconnect with clients or contacts.',
                'icon' => 'fas fa-mail-bulk',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Professional Email Responder',
                'category' => 'templates-email',
                'description' => 'Compose a professional response to inquiries, questions, or requests.',
                'icon' => 'fas fa-reply',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Press Release Writer',
                'category' => 'templates-email',
                'description' => 'Generate a press release to announce new products, events, or company updates.',
                'icon' => 'fas fa-bullhorn',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Cold Email Generator',
                'category' => 'templates-email',
                'description' => 'Create effective cold emails to reach out to potential clients or partners.',
                'icon' => 'fas fa-snowflake',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Personal Workout Plan Creator',
                'category' => 'templates-fitness-health',
                'description' => 'Design a personalized workout plan based on individual fitness goals and needs.',
                'icon' => 'fas fa-dumbbell',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Meal Plan Generator',
                'category' => 'templates-fitness-health',
                'description' => 'Develop a customized meal plan based on dietary preferences and nutritional needs.',
                'icon' => 'fas fa-utensils',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'eBook Creator',
                'category' => 'templates-writer',
                'description' => 'Generate a complete eBook on any topic, perfect for authors or marketers.',
                'icon' => 'fas fa-book-open',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Paragraph Writer',
                'category' => 'templates-writer',
                'description' => 'Create a well-written paragraph on any given topic to enhance content quality.',
                'icon' => 'fas fa-paragraph',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Creative Story Idea Generator',
                'category' => 'templates-writer',
                'description' => 'Generate unique story ideas or complete stories to inspire writers.',
                'icon' => 'fas fa-feather-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Book Ideas Generator',
                'category' => 'templates-writer',
                'description' => 'Develop ideas for new books or novels based on specified themes or genres.',
                'icon' => 'fas fa-book',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Content Enhancement Tool',
                'category' => 'templates-writer',
                'description' => 'Improve existing content by providing suggestions for enhancement and clarity.',
                'icon' => 'fas fa-edit',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'News Article Generator',
                'category' => 'templates-misc',
                'description' => 'Craft news articles from a journalist\'s perspective on current events.',
                'icon' => 'fas fa-pen-nib',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'RSS Feed Content Generator',
                'category' => 'templates-misc',
                'description' => 'Create unique content based on information extracted from an RSS feed.',
                'icon' => 'fas fa-rss',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI Content Detection',
                'category' => 'templates-misc',
                'description' => 'Generate content or responses that are indistinguishable from human-generated content.',
                'icon' => 'fas fa-robot',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Real Estate Listing Generator',
                'category' => 'templates-misc',
                'description' => 'Generate real estate listings for properties based on specified criteria.',
                'icon' => 'fas fa-home',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Creative Prompt Generator',
                'category' => 'templates-misc',
                'description' => 'Generate creative prompts to inspire writing, brainstorming, or idea generation.',
                'icon' => 'fas fa-lightbulb',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI Voice Isolator',
                'category' => 'templates-voice',
                'description' => 'Separate voices from background noise in audio recordings for clear output.',
                'icon' => 'fas fa-microphone-alt',
                'bg_color' => '#F5F5F7',
            ],
        ];

        // Insert all templates into the database
        DB::table('templates')->insert($templates);
    }
}

// [
//     'title' => 'AI Image Generator',
//     'category' => 'templates-development',
//     'description' => 'Unleash your creativity with our AI image generator that produces stunning visuals in seconds.',
//     'icon' => 'fas fa-image',
//     'bg_color' => '#F5F5F7',
// ],
// [
//     'title' => 'AI Speech to Text',
//     'category' => 'templates-blog',
//     'description' => 'The AI app that turns audio speech into text with ease. Get ready to generate custom texts from audio files quickly and accurately.',
//     'icon' => 'fas fa-microphone-alt',
//     'bg_color' => '#F5F5F7',
// ],
// [
//     'title' => 'AI Code Generator',
//     'category' => 'templates-development',
//     'description' => 'Create custom code in seconds! Leverage our state-of-the-art AI technology to quickly and easily generate code in any language.',
//     'icon' => 'fas fa-code',
//     'bg_color' => '#F5F5F7',
// ],
// [
//     'title' => 'AI Voiceover',
//     'category' => 'templates-voiceover',
//     'description' => 'The AI app that turns audio speech into text with ease. Get ready to generate custom texts from audio files quickly and accurately.',
//     'icon' => 'fas fa-microphone',
//     'bg_color' => '#F5F5F7',
// ],
// [
//     'title' => 'AI Vision',
//     'category' => 'templates-blog',
//     'description' => 'Elevate your visual analytics with our AI Vision platform. Harness the power of machine learning for real-time image recognition and data insights. Enhance efficiency and decision-making.',
//     'icon' => 'fas fa-eye',
//     'bg_color' => '#F5F5F7',
// ],
// [
//     'title' => 'AI YouTube',
//     'category' => 'templates-youtube',
//     'description' => 'Simply turn your YouTube videos into a Blog post.',
//     'icon' => 'fab fa-youtube',
//     'bg_color' => '#F5F5F7',
// ],
// [
//     'title' => 'AI Plagiarism Checker',
//     'category' => 'templates-blog',
//     'description' => 'Analyze text, comparing it against a vast database of online content to identify potential plagiarism.',
//     'icon' => 'fas fa-check-circle',
//     'bg_color' => '#F5F5F7',
// ],
// [
//     'title' => 'AI Video',
//     'category' => 'templates-video',
//     'description' => 'Bring your static images to life and create visually compelling videos effortlessly.',
//     'icon' => 'fas fa-video',
//     'bg_color' => '#F5F5F7',
// ],
// [
//     'title' => 'TikTok Video Caption Generator',
//     'category' => 'templates-social-media',
//     'description' => 'Generate captions for TikTok videos.',
//     'icon' => 'fas fa-comment-alt',
//     'bg_color' => '#F5F5F7',
// ],
// [
//     'title' => 'Facebook Video Script Creator',
//     'category' => 'templates-social-media',
//     'description' => 'Generate a script for a Facebook video.',
//     'icon' => 'fas fa-video',
//     'bg_color' => '#F5F5F7',
// ],
// [
//     'title' => 'Youtube Video Tag Generator',
//     'category' => 'templates-social-media',
//     'description' => 'Generate tags for YouTube videos.',
//     'icon' => 'fas fa-tags',
//     'bg_color' => '#F5F5F7',
// ],
// [
//     'title' => 'Video Content Idea Generator',
//     'category' => 'templates-social-media',
//     'description' => 'Generate ideas for video content.',
//     'icon' => 'fas fa-video',
//     'bg_color' => '#F5F5F7',
// ],
// [
//     'title' => 'Coding Education Material Creator',
//     'category' => 'templates-development',
//     'description' => 'Create educational materials and tutorials to teach coding concepts and techniques.',
//     'icon' => 'fas fa-chalkboard-teacher',
//     'bg_color' => '#F5F5F7',
// ],
// [
//     'title' => 'Changelog Generator',
//     'category' => 'templates-development',
//     'description' => 'Generate changelogs to document updates and modifications in software or projects.',
//     'icon' => 'fas fa-file-alt',
//     'bg_color' => '#F5F5F7',
// ], 
