<?php

namespace Database\Seeders; // Make sure this namespace is correct

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TemplatesSeeder extends Seeder
{
    public function run()
    {
        DB::table('templates')->insert([
            [
                'title' => 'Article Generator',
                'category' => 'templates-blog',
                'description' => 'Instantly create unique articles on any topic. Boost engagement, improve SEO, and save time.',
                'icon' => 'fas fa-newspaper',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Testimonial Review',
                'category' => 'templates-ecommerce',
                'description' => 'Instantly generate authentic testimonials. Build trust and credibility with genuine reviews.',
                'icon' => 'fas fa-star',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Blog Conclusion',
                'category' => 'templates-blog',
                'description' => 'End your blog posts on a high note. Craft memorable conclusions that leave a lasting impact.',
                'icon' => 'fas fa-bookmark',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Youtube Video Description',
                'category' => 'templates-social-media',
                'description' => 'Elevate your YouTube content with compelling video descriptions. Generate engaging descriptions effortlessly and increase views.',
                'icon' => 'fab fa-youtube',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Instagram Captions',
                'category' => 'templates-social-media',
                'description' => 'Elevate your Instagram game with captivating captions. Generate unique captions that engage followers and increase your reach.',
                'icon' => 'fab fa-instagram',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Social Media Post Tweet',
                'category' => 'templates-social-media',
                'description' => 'Make an impact with every tweet. Generate attention-grabbing social media posts and increase engagement.',
                'icon' => 'fab fa-twitter',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Facebook Headlines',
                'category' => 'templates-social-media',
                'description' => 'Get noticed with attention-grabbing Facebook headlines. Generate unique, clickable headlines that increase engagement and drive traffic.',
                'icon' => 'fab fa-facebook',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Google Ads Headlines',
                'category' => 'templates-advertisement',
                'description' => 'Create high-converting Google ads with captivating headlines. Generate unique, clickable ads that drive traffic and boost sales.',
                'icon' => 'fab fa-google',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Paragraph Generator',
                'category' => 'templates-blog',
                'description' => 'Generate a paragraph with keywords and description. Never struggle with writer\'s block again. Generate flawless paragraphs that captivate readers.',
                'icon' => 'fas fa-paragraph',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Pros & Cons',
                'category' => 'templates-development',
                'description' => 'Make informed decisions with ease. Generate unbiased pros and cons lists that help you weigh options and make better choices.',
                'icon' => 'fas fa-list',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Meta Description',
                'category' => 'templates-development',
                'description' => 'Get more clicks with compelling meta descriptions. Generate unique, SEO-friendly meta descriptions that attract customers and boost traffic.',
                'icon' => 'fas fa-clipboard',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Product Description',
                'category' => 'templates-ecommerce',
                'description' => 'Craft persuasive product descriptions that boost sales.',
                'icon' => 'fas fa-pen',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Article Generator',
                'category' => 'templates-blog',
                'description' => 'Instantly create unique articles on any topic. Boost engagement, improve SEO, and save time.',
                'icon' => 'fas fa-newspaper',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Testimonial Review',
                'category' => 'templates-ecommerce',
                'description' => 'Instantly generate authentic testimonials. Build trust and credibility with genuine reviews.',
                'icon' => 'fas fa-star',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Blog Conclusion',
                'category' => 'templates-blog',
                'description' => 'End your blog posts on a high note. Craft memorable conclusions that leave a lasting impact.',
                'icon' => 'fas fa-bookmark',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Youtube Video Description',
                'category' => 'templates-social-media',
                'description' => 'Elevate your YouTube content with compelling video descriptions. Generate engaging descriptions effortlessly and increase views.',
                'icon' => 'fab fa-youtube',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Instagram Captions',
                'category' => 'templates-social-media',
                'description' => 'Elevate your Instagram game with captivating captions. Generate unique captions that engage followers and increase your reach.',
                'icon' => 'fab fa-instagram',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Instagram Hashtags',
                'category' => 'templates-social-media',
                'description' => 'Boost your Instagram reach with relevant hashtags. Generate optimal, trending hashtags and increase your visibility.',
                'icon' => 'fab fa-instagram',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Social Media Post Tweet',
                'category' => 'templates-social-media',
                'description' => 'Make an impact with every tweet. Generate attention-grabbing social media posts and increase engagement.',
                'icon' => 'fab fa-twitter',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Social Media Post Business',
                'category' => 'templates-social-media',
                'description' => 'Generate a text for your business social media networks. Maximize your social media presence with impactful business posts.',
                'icon' => 'fas fa-building',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Facebook Headlines',
                'category' => 'templates-social-media',
                'description' => 'Get noticed with attention-grabbing Facebook headlines. Generate unique, clickable headlines that increase engagement and drive traffic.',
                'icon' => 'fab fa-facebook',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Google Ads Headlines',
                'category' => 'templates-advertisement',
                'description' => 'Create high-converting Google ads with captivating headlines. Generate unique, clickable ads that drive traffic and boost sales.',
                'icon' => 'fab fa-google',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Google Ads Description',
                'category' => 'templates-advertisement',
                'description' => 'Step up your Google ad game, Craft high-converting ad copy that grabs attention and drives sales.',
                'icon' => 'fab fa-google',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Paragraph Generator',
                'category' => 'templates-blog',
                'description' => 'Generate a paragraph with keywords and description. Never struggle with writer\'s block again. Generate flawless paragraphs that captivate readers.',
                'icon' => 'fas fa-paragraph',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Pros & Cons',
                'category' => 'templates-development',
                'description' => 'Make informed decisions with ease. Generate unbiased pros and cons lists that help you weigh options and make better choices.',
                'icon' => 'fas fa-list',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Meta Description',
                'category' => 'templates-development',
                'description' => 'Get more clicks with compelling meta descriptions. Generate unique, SEO-friendly meta descriptions that attract customers and boost traffic.',
                'icon' => 'fas fa-clipboard',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'FAQ Generator (All Datas)',
                'category' => 'templates-development',
                'description' => 'Quickly create helpful FAQs. Our AI-powered generator provides custom responses to common questions in seconds.',
                'icon' => 'fas fa-question-circle',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Email Generator',
                'category' => 'templates-email',
                'description' => 'Generate an email with your subject and description. Streamline your inbox and save time.',
                'icon' => 'fas fa-envelope',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Email Answer Generator',
                'category' => 'templates-email',
                'description' => 'Effortlessly tackle your overflowing inbox with custom, accurate responses to common queries, freeing you up to focus on what matters most.',
                'icon' => 'fas fa-reply',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Newsletter Generator',
                'category' => 'templates-email',
                'description' => 'Generate engaging newsletters easily with personalized content that resonates with your audience, driving growth and engagement.',
                'icon' => 'fas fa-newspaper',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Grammar Correction',
                'category' => 'templates-blog',
                'description' => 'Eliminate grammar errors and enhance your writing with ease. Our tool offers seamless grammar correction for flawless content.',
                'icon' => 'fas fa-spell-check',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'TL;DR Summarization',
                'category' => 'templates-blog',
                'description' => 'Automatically summarize long texts into bite-sized summaries with this TL;DR generator.',
                'icon' => 'fas fa-compress-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI Image Generator',
                'category' => 'templates-development',
                'description' => 'Unleash your creativity with our AI image generator that produces stunning visuals in seconds.',
                'icon' => 'fas fa-image',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI Speech to Text',
                'category' => 'templates-blog',
                'description' => 'The AI app that turns audio speech into text with ease. Get ready to generate custom texts from audio files quickly and accurately.',
                'icon' => 'fas fa-microphone-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI Code Generator',
                'category' => 'templates-development',
                'description' => 'Create custom code in seconds! Leverage our state-of-the-art AI technology to quickly and easily generate code in any language.',
                'icon' => 'fas fa-code',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI Voiceover',
                'category' => 'templates-voiceover',
                'description' => 'The AI app that turns audio speech into text with ease. Get ready to generate custom texts from audio files quickly and accurately.',
                'icon' => 'fas fa-microphone',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI Article Wizard Generator',
                'category' => 'templates-blog',
                'description' => 'Create custom articles instantly with our article wizard generator. Boost engagement and save time.',
                'icon' => 'fas fa-wizard-hat',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI Vision',
                'category' => 'templates-blog',
                'description' => 'Elevate your visual analytics with our AI Vision platform. Harness the power of machine learning for real-time image recognition and data insights. Enhance efficiency and decision-making.',
                'icon' => 'fas fa-eye',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'File Analyzer',
                'category' => 'templates-blog',
                'description' => 'Simply upload a file (PDF, CSV, .doc or .docx) and extract key insights or summarize the entire document.',
                'icon' => 'fas fa-file-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Chat Image',
                'category' => 'templates-blog',
                'description' => 'Generate Image by user input.',
                'icon' => 'fas fa-image',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI YouTube',
                'category' => 'templates-youtube',
                'description' => 'Simply turn your YouTube videos into a Blog post.',
                'icon' => 'fab fa-youtube',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI ReWriter',
                'category' => 'templates-blog',
                'description' => 'Rewrite more professional and detailed content instantly with our AI rewriter. Boost engagement and save time.',
                'icon' => 'fas fa-redo',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI RSS',
                'category' => 'templates-rss',
                'description' => 'Generate unique content with RSS Feed.',
                'icon' => 'fas fa-rss',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI Plagiarism Checker',
                'category' => 'templates-blog',
                'description' => 'Analyze text, comparing it against a vast database of online content to identify potential plagiarism.',
                'icon' => 'fas fa-check-circle',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI Content Detector',
                'category' => 'templates-blog',
                'description' => 'Analyze text, comparing it against a vast database of online content to detect AI writing content.',
                'icon' => 'fas fa-search',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI Video',
                'category' => 'templates-video',
                'description' => 'Bring your static images to life and create visually compelling videos effortlessly.',
                'icon' => 'fas fa-video',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI Web Chat',
                'category' => 'templates-blog',
                'description' => 'Analyze web page content with URL.',
                'icon' => 'fas fa-comments',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Cover Letter',
                'category' => 'templates-academic',
                'description' => 'Generate professional cover letters that highlight your strengths and stand out to employers.',
                'icon' => 'fas fa-file-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Math Question',
                'category' => 'templates-academic',
                'description' => 'Solve complex math questions with ease. Get step-by-step solutions and understand the process.',
                'icon' => 'fas fa-calculator',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Bullet Point Answer',
                'category' => 'templates-academic',
                'description' => 'Generate concise bullet point answers for any question. Save time and get straight to the point.',
                'icon' => 'fas fa-list-ul',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Thesis Statement',
                'category' => 'templates-academic',
                'description' => 'Generate a thesis statement for the given topic.',
                'icon' => 'fas fa-quote-right',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Proofreading',
                'category' => 'templates-academic',
                'description' => 'Proofread the given text and provide suggestions for improvement.',
                'icon' => 'fas fa-check',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Rephrase',
                'category' => 'templates-academic',
                'description' => 'Rephrase the given text to improve clarity and readability.',
                'icon' => 'fas fa-sync-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Improve',
                'category' => 'templates-academic',
                'description' => 'Improve the given text by enhancing its quality and clarity.',
                'icon' => 'fas fa-arrow-up',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Job Description',
                'category' => 'templates-business',
                'description' => 'Generate comprehensive job descriptions tailored to your company needs.',
                'icon' => 'fas fa-briefcase',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Resume Builder',
                'category' => 'templates-business',
                'description' => 'Create professional resumes tailored to your skills and experience.',
                'icon' => 'fas fa-file-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Linkedin',
                'category' => 'templates-business',
                'description' => 'Generate engaging LinkedIn profile descriptions that attract attention from employers and connections.',
                'icon' => 'fab fa-linkedin',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Startup Ideas (w/ quantities)',
                'category' => 'templates-business',
                'description' => 'Generate innovative startup ideas along with estimated quantities and market analysis.',
                'icon' => 'fas fa-lightbulb',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'PAS',
                'category' => 'templates-business',
                'description' => 'Generate Persuasion-Awareness-Solution (PAS) frameworks for persuasive communication strategies.',
                'icon' => 'fas fa-bullhorn',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Strategy',
                'category' => 'templates-business',
                'description' => 'Generate strategic plans and frameworks for business development and growth.',
                'icon' => 'fas fa-chart-line',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Personal Bio',
                'category' => 'templates-business',
                'description' => 'Generate compelling personal biographies for professional profiles and portfolios.',
                'icon' => 'fas fa-user',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Cost Benefit Analysis',
                'category' => 'templates-business',
                'description' => 'Conduct cost-benefit analyses to evaluate potential business decisions and investments.',
                'icon' => 'fas fa-balance-scale',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Brainstorming',
                'category' => 'templates-business',
                'description' => 'Generate creative ideas and solutions through structured brainstorming sessions.',
                'icon' => 'fas fa-brain',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Linkedin Post',
                'category' => 'templates-business',
                'description' => 'Craft engaging and professional posts for sharing on LinkedIn.',
                'icon' => 'fab fa-linkedin',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Sales Pitch',
                'category' => 'templates-business',
                'description' => 'Craft persuasive sales pitches to attract potential clients and investors.',
                'icon' => 'fas fa-handshake',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Social Media Reply',
                'category' => 'templates-customer-service',
                'description' => 'Craft effective and professional replies to social media comments and messages.',
                'icon' => 'fas fa-reply',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Ticket Reply',
                'category' => 'templates-customer-service',
                'description' => 'Generate professional replies for customer support tickets.',
                'icon' => 'fas fa-ticket-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Song Lyrics',
                'category' => 'templates-entertainment',
                'description' => 'Generate creative and original song lyrics for any genre.',
                'icon' => 'fas fa-music',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Jokes',
                'category' => 'templates-entertainment',
                'description' => 'Create funny and entertaining jokes.',
                'icon' => 'fas fa-laugh',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Event Planner',
                'category' => 'templates-entertainment',
                'description' => 'Plan a detailed event itinerary.',
                'icon' => 'fas fa-calendar-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Travel Planner',
                'category' => 'templates-entertainment',
                'description' => 'Create a detailed travel itinerary for any destination.',
                'icon' => 'fas fa-plane-departure',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Gift Ideas',
                'category' => 'templates-entertainment',
                'description' => 'Generate creative and personalized gift ideas.',
                'icon' => 'fas fa-gift',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Product Description',
                'category' => 'templates-ecommerce',
                'description' => 'Create detailed and appealing product descriptions.',
                'icon' => 'fas fa-box',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Product Features',
                'category' => 'templates-ecommerce',
                'description' => 'Highlight the key features of a product.',
                'icon' => 'fas fa-list',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Product Name Ideas',
                'category' => 'templates-ecommerce',
                'description' => 'Generate creative and catchy product name ideas.',
                'icon' => 'fas fa-tags',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Why Choose This Product',
                'category' => 'templates-ecommerce',
                'description' => 'Explain why a customer should choose a specific product.',
                'icon' => 'fas fa-thumbs-up',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Reviews',
                'category' => 'templates-ecommerce',
                'description' => 'Generate detailed reviews for a product.',
                'icon' => 'fas fa-clipboard-list',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Review Responder',
                'category' => 'templates-ecommerce',
                'description' => 'Craft professional responses to customer reviews.',
                'icon' => 'fas fa-comment-dots',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Sitemap',
                'category' => 'templates-website',
                'description' => 'Generate a comprehensive sitemap for your website.',
                'icon' => 'fas fa-sitemap',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Tagline',
                'category' => 'templates-website',
                'description' => 'Create a catchy and memorable tagline for your website.',
                'icon' => 'fas fa-tag',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'UX Ideas',
                'category' => 'templates-website',
                'description' => 'Generate innovative UX ideas to improve user experience.',
                'icon' => 'fas fa-lightbulb',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Design Ideas',
                'category' => 'templates-website',
                'description' => 'Get creative design ideas for your website.',
                'icon' => 'fas fa-paint-brush',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Services Page',
                'category' => 'templates-website',
                'description' => 'Create detailed content for your services page.',
                'icon' => 'fas fa-concierge-bell',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Features Page',
                'category' => 'templates-website',
                'description' => 'Create detailed content for your features page.',
                'icon' => 'fas fa-star',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Keyword Generator',
                'category' => 'templates-website',
                'description' => 'Generate relevant keywords for your website content.',
                'icon' => 'fas fa-key',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Keyword Extractor',
                'category' => 'templates-website',
                'description' => 'Extract important keywords from your website content.',
                'icon' => 'fas fa-search',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'SEO',
                'category' => 'templates-website',
                'description' => 'Optimize your website content for search engines.',
                'icon' => 'fas fa-search-plus',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Testimonials',
                'category' => 'templates-website',
                'description' => 'Generate authentic testimonials for your website.',
                'icon' => 'fas fa-comments',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Landing Page Content - Copywriting',
                'category' => 'templates-website',
                'description' => 'Create compelling copy for your landing page.',
                'icon' => 'fas fa-copy',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Website - Copywriting',
                'category' => 'templates-website',
                'description' => 'Create engaging copy for your website pages.',
                'icon' => 'fas fa-feather-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'FAQ',
                'category' => 'templates-website',
                'description' => 'Generate frequently asked questions for your website.',
                'icon' => 'fas fa-question-circle',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Call to Action',
                'category' => 'templates-website',
                'description' => 'Create compelling calls to action for your website.',
                'icon' => 'fas fa-bullhorn',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Meta Description',
                'category' => 'templates-website',
                'description' => 'Generate meta descriptions for your website pages.',
                'icon' => 'fas fa-info-circle',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Rewrite with Keywords',
                'category' => 'templates-website',
                'description' => 'Rewrite website content with targeted keywords.',
                'icon' => 'fas fa-edit',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Privacy Policy',
                'category' => 'templates-website',
                'description' => 'Generate a privacy policy for your website.',
                'icon' => 'fas fa-user-secret',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Terms and Conditions',
                'category' => 'templates-website',
                'description' => 'Generate terms and conditions for your website.',
                'icon' => 'fas fa-file-contract',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Blog Ideas',
                'category' => 'templates-blog',
                'description' => 'Generate creative ideas for your next blog post.',
                'icon' => 'fas fa-pencil-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Blog Intro',
                'category' => 'templates-blog',
                'description' => 'Generate an engaging introduction for your blog post.',
                'icon' => 'fas fa-quote-left',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Blog Section',
                'category' => 'templates-blog',
                'description' => 'Generate a section for your blog post.',
                'icon' => 'fas fa-paragraph',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Blog Outline',
                'category' => 'templates-blog',
                'description' => 'Generate an outline for your blog post.',
                'icon' => 'fas fa-tasks',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Blog Article',
                'category' => 'templates-blog',
                'description' => 'Generate a full article for your blog post.',
                'icon' => 'fas fa-newspaper',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'IG Reel Script',
                'category' => 'templates-social-media',
                'description' => 'Generate a script for an Instagram Reel video.',
                'icon' => 'fas fa-video',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'IG Captions',
                'category' => 'templates-social-media',
                'description' => 'Generate captions for Instagram posts.',
                'icon' => 'fab fa-instagram',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'TikTok Script',
                'category' => 'templates-social-media',
                'description' => 'Generate a script for a TikTok video.',
                'icon' => 'fab fa-tiktok',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'TikTok Video Caption',
                'category' => 'templates-social-media',
                'description' => 'Generate captions for TikTok videos.',
                'icon' => 'fas fa-comment-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Facebook Post',
                'category' => 'templates-social-media',
                'description' => 'Generate engaging posts for Facebook.',
                'icon' => 'fab fa-facebook',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Facebook Headlines',
                'category' => 'templates-social-media',
                'description' => 'Generate attention-grabbing headlines for Facebook.',
                'icon' => 'fas fa-heading',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Facebook Video Script',
                'category' => 'templates-social-media',
                'description' => 'Generate a script for a Facebook video.',
                'icon' => 'fas fa-video',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'X Tweet',
                'category' => 'templates-social-media',
                'description' => 'Generate a tweet for any purpose.',
                'icon' => 'fab fa-twitter',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'X Thread',
                'category' => 'templates-social-media',
                'description' => 'Generate a Twitter thread for any topic.',
                'icon' => 'fas fa-comments',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Youtube Video Title',
                'category' => 'templates-social-media',
                'description' => 'Generate titles for YouTube videos.',
                'icon' => 'fab fa-youtube',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Youtube Video Description',
                'category' => 'templates-social-media',
                'description' => 'Generate descriptions for YouTube videos.',
                'icon' => 'fas fa-clipboard-list',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Youtube Video Tag',
                'category' => 'templates-social-media',
                'description' => 'Generate tags for YouTube videos.',
                'icon' => 'fas fa-tags',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Youtube Video to Blog Post',
                'category' => 'templates-social-media',
                'description' => 'Generate blog posts from YouTube videos.',
                'icon' => 'fas fa-blog',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Video Idea',
                'category' => 'templates-social-media',
                'description' => 'Generate ideas for video content.',
                'icon' => 'fas fa-video',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Video Description',
                'category' => 'templates-social-media',
                'description' => 'Generate descriptions for videos.',
                'icon' => 'fas fa-file-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Viral Tweet Idea',
                'category' => 'templates-social-media',
                'description' => 'Generate ideas for tweets that could potentially go viral.',
                'icon' => 'fab fa-twitter',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Clickbait Titles',
                'category' => 'templates-social-media',
                'description' => 'Generate clickbait titles for social media posts.',
                'icon' => 'fas fa-bullhorn',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'FB Ad',
                'category' => 'templates-advertising',
                'description' => 'Generate content for Facebook advertisements.',
                'icon' => 'fab fa-facebook',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Google Ad',
                'category' => 'templates-advertising',
                'description' => 'Generate content for Google advertisements.',
                'icon' => 'fab fa-google',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'TV Ads',
                'category' => 'templates-advertising',
                'description' => 'Generate ideas and content for TV advertisements.',
                'icon' => 'fas fa-tv',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Youtube Ads',
                'category' => 'templates-advertising',
                'description' => 'Generate ideas and content for YouTube advertisements.',
                'icon' => 'fab fa-youtube',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Translate',
                'category' => 'templates-languages',
                'description' => 'Translate text from one language to another.',
                'icon' => 'fas fa-language',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Grammar Check',
                'category' => 'templates-languages',
                'description' => 'Check grammar and provide suggestions for improvement.',
                'icon' => 'fas fa-spell-check',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'List Synonyms',
                'category' => 'templates-languages',
                'description' => 'Generate a list of synonyms for a given word.',
                'icon' => 'fas fa-th-list',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Learn New Words',
                'category' => 'templates-languages',
                'description' => 'Discover and learn new words with their meanings and usage.',
                'icon' => 'fas fa-book',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Bug Fix',
                'category' => 'templates-development',
                'description' => 'Identify and fix bugs in code to improve functionality and performance.',
                'icon' => 'fas fa-bug',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Explain Code',
                'category' => 'templates-development',
                'description' => 'Provide explanations and clarifications on specific sections of code.',
                'icon' => 'fas fa-code',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Teach Code',
                'category' => 'templates-development',
                'description' => 'Create educational materials and tutorials to teach coding concepts and techniques.',
                'icon' => 'fas fa-chalkboard-teacher',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Changelog Creator',
                'category' => 'templates-development',
                'description' => 'Generate changelogs to document updates and modifications in software or projects.',
                'icon' => 'fas fa-file-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Welcome Email',
                'category' => 'templates-email',
                'description' => 'Craft a warm and engaging email to welcome new subscribers or users.',
                'icon' => 'fas fa-envelope-open-text',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Invitation Mail',
                'category' => 'templates-email',
                'description' => 'Create an inviting email to send out invitations for events, gatherings, or meetings.',
                'icon' => 'fas fa-envelope',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Follow up Email',
                'category' => 'templates-email',
                'description' => 'Craft a follow-up email to reconnect with clients, customers, or contacts.',
                'icon' => 'fas fa-mail-bulk',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Reply Email',
                'category' => 'templates-email',
                'description' => 'Compose a professional email response to reply to inquiries, questions, or requests.',
                'icon' => 'fas fa-reply',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Newsletter',
                'category' => 'templates-email',
                'description' => 'Design and create a newsletter to share updates, news, or promotions with subscribers.',
                'icon' => 'fas fa-newspaper',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Press Release',
                'category' => 'templates-email',
                'description' => 'Write a press release to announce new products, events, or company updates.',
                'icon' => 'fas fa-bullhorn',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Cold Email',
                'category' => 'templates-email',
                'description' => 'Create an effective cold email to reach out to potential clients or partners.',
                'icon' => 'fas fa-snowflake',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Create a Workout Plan',
                'category' => 'templates-fitness-health',
                'description' => 'Design a personalized workout plan tailored to individual needs and fitness goals.',
                'icon' => 'fas fa-dumbbell',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Create a Meal Plan',
                'category' => 'templates-fitness-health',
                'description' => 'Develop a customized meal plan based on dietary preferences, nutritional needs, and health goals.',
                'icon' => 'fas fa-utensils',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'eBook',
                'category' => 'templates-writer',
                'description' => 'Generate a complete eBook on any topic of your choice.',
                'icon' => 'fas fa-book-open',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Paragraph',
                'category' => 'templates-writer',
                'description' => 'Generate a well-written paragraph on any given topic.',
                'icon' => 'fas fa-paragraph',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Story Generator',
                'category' => 'templates-writer',
                'description' => 'Generate creative story ideas or complete stories based on provided prompts.',
                'icon' => 'fas fa-feather-alt',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Book Ideas',
                'category' => 'templates-writer',
                'description' => 'Generate ideas for new books or novels based on specified themes or genres.',
                'icon' => 'fas fa-book',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Content Improver',
                'category' => 'templates-writer',
                'description' => 'Enhance the quality and readability of existing content by providing suggestions for improvement.',
                'icon' => 'fas fa-edit',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Explain to a Child',
                'category' => 'templates-misc',
                'description' => 'Simplify complex topics or concepts to make them understandable to children.',
                'icon' => 'fas fa-child',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Write News From a Journalist Point of View',
                'category' => 'templates-misc',
                'description' => 'Craft news articles from the perspective of a journalist.',
                'icon' => 'fas fa-pen-nib',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Generate From RSS Feed',
                'category' => 'templates-misc',
                'description' => 'Generate content based on the information extracted from a provided RSS feed.',
                'icon' => 'fas fa-rss',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Undetectable AI',
                'category' => 'templates-misc',
                'description' => 'Generate content or responses that are indistinguishable from human-generated content.',
                'icon' => 'fas fa-robot',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Pros and Cons',
                'category' => 'templates-misc',
                'description' => 'Generate a list of pros and cons for any given topic.',
                'icon' => 'fas fa-balance-scale',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Real Estate Listing',
                'category' => 'templates-misc',
                'description' => 'Generate real estate listings for properties based on specified criteria.',
                'icon' => 'fas fa-home',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'Prompt Generator',
                'category' => 'templates-misc',
                'description' => 'Generate creative prompts to inspire writing, brainstorming, or idea generation.',
                'icon' => 'fas fa-lightbulb',
                'bg_color' => '#F5F5F7',
            ],
            [
                'title' => 'AI Voice Isolator',
                'category' => 'templates-voice',
                'description' => 'Separate voices from background noise in audio recordings.',
                'icon' => 'fas fa-microphone-alt',
                'bg_color' => '#F5F5F7',
            ],
        ]);
    }
}
 
